// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0nHSJd8koUR4XxTOjdmph28gbCc-jQWs',
    appId: '1:720289701165:web:4f322a78856ae6595c47a4',
    messagingSenderId: '720289701165',
    projectId: 'pushnotitutorial-cf120',
    authDomain: 'pushnotitutorial-cf120.firebaseapp.com',
    storageBucket: 'pushnotitutorial-cf120.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWWAhkcf8G0KukKNzdGS0M5Wz_y0RY72k',
    appId: '1:720289701165:android:fd4475f0f4509be55c47a4',
    messagingSenderId: '720289701165',
    projectId: 'pushnotitutorial-cf120',
    storageBucket: 'pushnotitutorial-cf120.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAYtxvx7UFQOYQmPaXEfgzKHWBZs4m_ak',
    appId: '1:720289701165:ios:1de5773df310f4f75c47a4',
    messagingSenderId: '720289701165',
    projectId: 'pushnotitutorial-cf120',
    storageBucket: 'pushnotitutorial-cf120.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAYtxvx7UFQOYQmPaXEfgzKHWBZs4m_ak',
    appId: '1:720289701165:ios:1de5773df310f4f75c47a4',
    messagingSenderId: '720289701165',
    projectId: 'pushnotitutorial-cf120',
    storageBucket: 'pushnotitutorial-cf120.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0nHSJd8koUR4XxTOjdmph28gbCc-jQWs',
    appId: '1:720289701165:web:6532699acdf5efd25c47a4',
    messagingSenderId: '720289701165',
    projectId: 'pushnotitutorial-cf120',
    authDomain: 'pushnotitutorial-cf120.firebaseapp.com',
    storageBucket: 'pushnotitutorial-cf120.appspot.com',
  );
}
